language: python
python:
- '3.4'
before_script:
# Credits to ACE3 for these validators
- wget https://www.dropbox.com/s/a3jchkwcrmkb59j/config_style_checker.py
- wget https://www.dropbox.com/s/ymydy777t20q1we/sqf_validator.py
script:
- python3 sqf_validator.py
- python3 config_style_checker.py
	
